### ISSUE TITLE
Fixing the cards, CSS and light mode dark mode

### ISSUE THREAD

**Issue by Anupamgupt** [bluelearn-open-source/blue-quotes#10]

**Comment by ShubhamYadav7063** [comment]
If this is not fixed @VG-1 can I work on this?

**Comment by VG-1** [comment]
@Anupamgupt are you working on it?

**Comment by VG-1** [comment]
Yeah @ShubhamYadav7063 you can work on it.

**Comment by ShubhamYadav7063** [comment]
@VG-1 just made a pr to fix this issue. Please check it out.
