### ISSUE TITLE
Add a dark mode button

### ISSUE THREAD

**Issue by VG-1** [bluelearn-open-source/blue-quotes#5]

**Comment by Anupamgupt** [comment]
Can u assign me the work

**Comment by VG-1** [comment]
sure @Anupamgupt go ahead.
all the best

**Comment by sumit-022** [comment]
Please assign this to me. I can do it.

**Comment by Anupamgupt** [comment]
Hey @VG-1  I have completed the work  and made the PR kindly see to it

**Comment by Sritam28** [comment]
Hey, @VG-1 could you please assign me this task.

**Comment by VG-1** [comment]
its done @Sritam28
